run_test error1
run_test if_sub
run_test_stdin if_sub_embed
run_test_stdin simple_sub1
run_test simple_sub2
run_test_stdin weird_sub
#run_test sub_hard_block
#run_test ultra_hell_sub
run_test error2
run_test_stdin if_sub1
run_test_stdin simple_sub
run_test_stdin sub_embed
run_test error3
run_test error4
run_test_stdin sub2.test
run_test_stdin sub3.test
run_test_stdin sub4.test
run_test_stdin sub5.test
run_test_stdin sub6.test
run_test_stdin sub7.test
run_test_stdin sub8.test
run_test_stdin sub9.test
run_test_stdin sub10.test
run_test_stdin sub11.test
run_test_stdin sub12.test
run_test_stdin sub13.test
run_test_stdin sub14.test
run_test_stdin sub15.test
run_test_stdin sub16.test
#run_test sub17.test
run_test sub_sub1.test
run_test_redirect sub_redir_pipe
run_test_stdin sub_stdin
