run_test normal1_func
run_test normal2_func
run_test_stdin normal3_func
run_test_stdin normal4_func
run_test fail1_func
run_test fail2_func
run_test fail3_func
run_test_redirect redir1_func
run_test_redirect redir2_func
run_test hard1_func
run_test hard2_func
run_test hard3_func
run_test_stdin dollar_args_func
run_test_stdin star_args_func
run_test_stdin simple_args_func
run_test break_func1
run_test break_func2
run_test unset_func
run_test leak_func
run_test args_restore_func arg1 arg2 arg3
run_test hard_arg_func firstarg1 firstarg2
