run_test echo/echo_args
run_test echo/echo_e
run_test echo/echo_e_backslash3
run_test echo/echo_mix_options2
run_test echo/echo_E
run_test echo/echo_E_backslash3
run_test echo/echo_n
run_test echo/echo_e_backslash1
run_test echo/echo_many_args
run_test_stdin echo/echo_simple
run_test echo/echo_bad_option1
run_test echo/echo_E_backslash1
run_test echo/echo_eEe
run_test echo/echo_many_e_E1
run_test echo/echo_bad_option2
run_test_stdin echo/echo_e_backslash2
run_test echo/echo_EeE
run_test echo/echo_many_e_E2
run_test echo/two_echos
run_test echo/echo_big_arg
run_test echo/echo_E_backslash2
run_test echo/echo_mix_options1
run_test true_false/false
run_test_stdin true_false/indecisive1
run_test true_false/quoted_builtin
run_test true_false/false_args
run_test true_false/indecisive2
run_test true_false/true
run_test true_false/true_args
